version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1
      - image: circleci/postgres:11-alpine-ram

      - image: redis:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
# version: 2.1
# orbs:
#   node: circleci/node@5
#   postgres: circleci/postgres@1.1.0
#   win: circleci/windows@4.1.1

# jobs:
#   installingPackages:
#     executor:
#       name: win/default # executor type
#       size: medium

#     steps:
#       - checkout
#       - run: npm install
#       - run: node server.js

#   # test:
#   #   executor:
#   #     name: win/default # executor type
#   #     size: medium

#   #   steps:
#   #     - checkout
#   #     - run: npm install
#   #     - run: npm test

# workflows:
#   version: 2.1
#   test_coverage:
#     jobs:
#       - installingPackages
#       # - test
