version: 2.1
orbs:
  node: circleci/node@5
  win: circleci/windows@4.1.1

jobs:
  installingPackages:
    executor:
      name: win/default # executor type
      size: medium

    steps:
      - checkout
      - run: npm install

  test:
    executor:
      name: win/default # executor type
      size: medium

    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2.1
  test_coverage:
    jobs:
      - installingPackages
      - test
